### ISSUE TITLE
Matrix portal is flashing double red after loading code.py

### ISSUE THREAD

**Issue by ees-dc** [metro-sign/dc-metro#15]
Overall, I've found all the instructions really clear for how to complete this project. I also have read through all the issues threads to see if I could fine any solutions there, but no dice. 

The issue I'm having is with loading the src files. By individually dragging over files, I've isolated the issue to the code.py file. As soon as I drag in the code.py file to the CIRCUITPY folder, the matrix portal starts flashing a double red light. As soon as I delete this file, the led returns to green. Unfortunately, I do not know anything about coding, so I cannot begin to identify or fix the issue (assuming it is a coding issue).

The circuit python version is 8.0.5. Any help would be greatly appreciated!

**Comment by enemes1** [comment]
I am having the same issue.  Does your RGB board have any activity?  Nothing lights up on the board after uploading 8.0.5.

**Comment by ees-dc** [comment]
No, to my knowledge nothing on the board is lighting up, but the
instructions also don't suggest checking until after the code.py file is
loaded.

**Comment by ees-dc** [comment]
Okay, I revisited this and re-read one of the other issue threads and have used the fork. I edited the config file as discussed and the code started working. However, I'm now stuck getting a crash error referenced in issue #10.
