### ISSUE TITLE
Unzipping lib.zip

### ISSUE THREAD

**Issue by carey-james** [metro-sign/dc-metro#2]
I ran into some trouble unzipping _lib.zip_ on my Matrix Portal M4 using macOS Catalina, getting errors when I attempted to unzip using the default method of double-clicking with Archive Utility. Instead, I had to go to the storage in terminal and use the 'unzip' command there. Think it has to do with filesize and the limited ram on the Matrix Portal. Might be worth adding to the README if this is a common issue.

**Comment by metro-sign** [comment]
Thanks for letting me know! Added a section in the documentation to provide a workaround: [Commit 734e5f](https://github.com/metro-sign/dc-metro/commit/734e5f9564878496917432b39cb360c440e677b1)

**Comment by gazunder** [comment]
cc: @metro-sign @carey-james 
I also had this same issue (Matrix Portal M4 on macOS). For me the issue was that `5x7.bdf` would not copy over. This file is relatively large (25905 lines long) and would cause the Matrix Portal M4 to reboot. I had to write this file out in 10k line increments. I did this by running:

```
sed -n -e 1,10000p 5x7.bdf >> /Volumes/CIRCUITPY/lib/5x7.bdf
sed -n -e 10001,20000p 5x7.bdf >> /Volumes/CIRCUITPY/lib/5x7.bdf
sed -n -e 20001,30001p 5x7.bdf >> /Volumes/CIRCUITPY/lib/5x7.bdf
```

Maybe this can help someone else who is having this issue.

**Comment by carey-james** [comment]
It looks like adafruit has some info about this on their troubleshooting page, attributing it to the hidden files made by macOS during copying/unzipping, their suggested solution is to stop the OS from making hidden files on the drive altogether. 
https://learn.adafruit.com/adafruit-feather-m4-express-atsamd51/troubleshooting (scroll down to "MacOS loves to add extra files.")

**Comment by curleebs** [comment]
Hi, I'm having difficulty on step 3. The folder lib is completely empty, and there isn't a zip folder. I'm on a computer with Windows 10, so I don't know if that's the issue. Please help!

**Comment by laurentruong** [comment]
Similar issue as @curleebs . Help would be great!

**Comment by GrayDeBerry** [comment]
Having the same issue as @curleebs and @laurentruong. Did either of you find a solution? I'm on MacOS Ventura 13.2

**Comment by k5cents** [comment]
@curleebs @laurentruong Pretty late, but if anybody is running into the same problem the instructions refer to `lib.zip` in _this_ repository (not in the new CIRCUITPY directory). You need to clone this repository to your computer and move the files over from there!

**Comment by Mathiasgyjr** [comment]
@kiernann Im hitting the snag where the lib folder is empty. How do I clone the repository?

**Comment by k5cents** [comment]
The lib folder on the device is supposed to be empty. Clone this repository and move the contents of _this_ `lib.zip` file onto the device. 

Cloning the repository simply means downloading it to your computer where you can move the files around.

https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository

**Comment by Mathiasgyjr** [comment]
@kiernann thanks for the last tip. Hoping last question/issue is I cant figure out how to: **Copy all of the Python files from src in this repository into the root of the CIRCUITPY volume._**

**Comment by k5cents** [comment]
Once you clone the repository to your computer, that means the `src` folder in this repository will also be on your machine. Take all the files in there (`*.py` python files) and move them onto the device. The "root" just means the very top, so they aren't inside a folder. That means they should be next to the new `lib` folder on the device (not inside it).

**Comment by Mathiasgyjr** [comment]
<img width="1729" alt="Screenshot 2023-03-24 at 8 57 24 PM" src="https://user-images.githubusercontent.com/128867339/227670942-e3448921-d2c5-470e-8031-70dea1b2d27a.png">

@kiernann I moved all the files over but nothing happened on the screen.....

**Comment by k5cents** [comment]
I would explore the solutions in issue #9 or #10.

Either use the older firmware or the newer libraries like those found in the forked version by @ScottKekoaShay ([ScottKekoaShay/dc-metro](https://github.com/ScottKekoaShay/dc-metro)).
