### ISSUE TITLE
Board not displaying anything end of part 2

### ISSUE THREAD

**Issue by GarlicPancake** [metro-sign/dc-metro#6]
Hello,

After dragging in the file to flash the board, the board went all black and is not displaying anything anymore. I have the lib file decompressed that is given by the owner of this project. I also have the py files from the src folder in it.

**Comment by scottiegarcia** [comment]
There's some incompatibility with the latest version of CircuitPython. Download v6.3.0 from S3 [here](https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/matrixportal_m4/en_US/)
